---
title: "GDINA thing"
author: "Wanjing Anya Ma"
date:  "`r Sys.Date()`"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
    
---

# Data Preprocessing
## Load Packages
Let's first load the packages that we need for this chapter. 

```{r, message=FALSE, warning = FALSE, echo = FALSE}
library("knitr") # for rendering the RMarkdown file
library("tidyverse") # for data wrangling 
library(dplyr)
library(mirt)
library('ggpubr')
library(Metrics)
library(hash)
library(ggplot2)
library(GGally)
library(gridExtra)
library(rstudioapi)
library(TAM)
library(mgcv)
library(GDINA)
library(MASS)
library(imv)
remotes::install_github("hansorlee/irwpkg")
library("irw")
```
```{r}
source("bd/00funs.R")
```

```{r}
hist(rowMeans(frac20$Q))
```

```{r}
Q <- sim30GDINA$simQ
K <- ncol(Q)
diverg <- list(c(1,2),
c(2,3),
c(1,4),
c(4,5))
linear <- list(c(1,2), c(2,3), c(3,4), c(4,5))
struc <- att.structure(diverg,K)
#struc <- att.structure(linear,K)
set.seed(123)
# data simulation
N <- 1000
true.lc <- sample(c(1:2^K),N,replace=TRUE,prob=struc$att.prob)

true.att <- attributepattern(K)[true.lc,]
gs <- matrix(rep(0.1,2*nrow(Q)),ncol=2)

# data simulation
simD <- simGDINA(N,Q,gs.parm = gs, model = "GDINA",attribute = true.att)

dat <-simD$dat #extract(simD,"dat")

resp <- as.data.frame(dat)
names(resp)<-paste("i",1:ncol(resp),sep='')
```


```{r}
J <- nrow(Q)  # number of items
co <- simD$catprob.parm
p<-list()

for (i in 1:nrow(Q)) {
    ii<-which(Q[i,]==1)
    z<-true.att[,ii,drop=FALSE]
    nms<-names(co[[i]])
    cats<-gsub(")","",gsub("P(","",nms,fixed=TRUE),fixed=TRUE)
    cats<-strsplit(cats,"")
    cats<-lapply(cats,as.numeric)
    cats<-do.call("rbind",cats)
    pr<-list()
    for (j in 1:nrow(cats)) {
      y<-cats[j,]

      z2<-z
      for (k in 1:ncol(z2)) if (y[k]==1) z2[,k]<-z[,k] else z2[,k]<-1-z[,k]
       #print(z2)
      pr[[j]]<-apply(z2,1,prod)
      
    }
    
    pr<-do.call("cbind",pr)
    p[[i]]<-pr %*% matrix(co[[i]],ncol=1)
   
  }
  p.true <- do.call("cbind", p)
  
```

# linear
```{r}
oos.compare.update(resp,Q,p.true,nfolds=5,modeltype = "GDINA",estmethod = "mp") 
```
# divergent 
```{r}
oos.compare.update(resp,Q,p.true,nfolds=5,modeltype = "GDINA",estmethod = "mp") 
```

```{r}
oos.compare.newresp(resp,Q,p.true, modeltype = "GDINA",estmethod = "mp") 
```

```{r}
oos.compare.newresp(resp,Q,p.true, modeltype = "GDINA",estmethod = "mp") 
```


```{r}
# Set parameters
nsk <- 6          # number of skills/attributes per row
n_valid <- 44     # desired number of valid rows

# Initialize an empty matrix to store valid rows
valid_rows <- matrix(nrow = 0, ncol = nsk)

# Loop until we have 50 valid rows
while (nrow(valid_rows) < n_valid) {
  candidate <- rbinom(nsk, 1, 0.5)  # Generate one candidate row
  if (all(candidate == 0)) next      # Skip if the row is all 0s
  valid_rows <- rbind(valid_rows, candidate)
}

# Create the identity matrix
I_k <- diag(nsk)

# Combine the identity matrix with the 50 valid rows to form the Q-matrix
q_matrix <- rbind(I_k, valid_rows)

# Display the resulting Q-matrix

rownames(q_matrix) <- NULL
q_matrix
```

# Frac20 data structure 
```{r}
library(ggcorrplot)
```

```{r}
response_df <- frac20$dat
cor_matrix_spearman <- cor(response_df, use = "pairwise.complete.obs", method = "pearson")
# Plot heatmap
ggcorrplot(cor_matrix_spearman, 
           lab = TRUE,               # Show correlation values
           lab_size = 2,             # Font size for labels
           #method = "square",        # Square tiles
           #type = "lower",           # Show only lower triangle
           colors = c("blue", "white", "red"), # Color scale
           title = "Item Correlation Heatmap",
           ggtheme = theme_minimal())
```
```{r}
total_correct <- colSums(response_df)
total_correct
```
```{r}
response_df
```

```{r}
response_matrix <- matrix(sample(0:1, 50, replace = TRUE), nrow = 10, ncol = 5)
colnames(response_matrix) <- paste0("Item", 1:5)

# Convert to dataframe
response_df <- as.data.frame(response_matrix)
response_df
```
```{r}
library(igraph)
library(ggraph)
library(viridis)  # For viridis color scale

```

```{r}

response_matrix <- as.matrix(sapply(response_df, as.numeric))

# Compute co-occurrence matrix
co_occurrence_matrix <- t(response_matrix) %*% response_matrix
# Compute co-occurrence matrix: Students who got both items corr
edge_list <- as.data.frame(as.table(co_occurrence_matrix))
colnames(edge_list) <- c("Item1", "Item2", "Weight")

# Remove self-loops and low-weight edges if necessary
#edge_list <- edge_list[edge_list$Item1 != edge_list$Item2 & edge_list$Percentage > 0.05, ]
edge_list <- edge_list[edge_list$Item1 != edge_list$Item2 & edge_list$Weight > 0, ]
edge_list <- edge_list %>% filter(Weight > 200)
# Create graph object
graph <- graph_from_data_frame(edge_list, directed = FALSE)

# Plot the network graph
ggraph(graph, layout = "fr") + 
  geom_edge_link(aes(color = Weight), alpha = 0.5) +  # Use 'Weight' for both width & color
  geom_node_point(size = 5) + 
  geom_node_text(aes(label = name), repel = TRUE) +
  scale_edge_color_viridis() +  # Correct function name
  scale_edge_width_continuous(range = c(0.5, 5)) +  # Adjust thickness
  theme_minimal() +
  ggtitle("Network Graph of Item Co-occurrence")
```

```{r}
frac20$Q

response_Q <- frac20$Q
cor_matrix_spearman <- cor(response_Q, use = "pairwise.complete.obs", method = "pearson")
# Plot heatmap
ggcorrplot(cor_matrix_spearman, 
           lab = TRUE,               # Show correlation values
           lab_size = 2,             # Font size for labels
           #method = "square",        # Square tiles
           #type = "lower",           # Show only lower triangle
           colors = c("blue", "white", "red"), # Color scale
           title = "Item Correlation Heatmap",
           ggtheme = theme_minimal())

response_matrix <- as.matrix(sapply(response_Q, as.numeric))

# Compute co-occurrence matrix
co_occurrence_matrix <- t(response_matrix) %*% response_matrix
# Compute co-occurrence matrix: Students who got both items corr
edge_list <- as.data.frame(as.table(co_occurrence_matrix))
colnames(edge_list) <- c("Item1", "Item2", "Weight")

# Remove self-loops and low-weight edges if necessary
#edge_list <- edge_list[edge_list$Item1 != edge_list$Item2 & edge_list$Percentage > 0.05, ]
edge_list <- edge_list[edge_list$Item1 != edge_list$Item2 & edge_list$Weight > 0, ]
# Create graph object
graph <- graph_from_data_frame(edge_list, directed = FALSE)

# Plot the network graph
ggraph(graph, layout = "fr") + 
  geom_edge_link(aes(color = Weight), alpha = 0.5) +  # Use 'Weight' for both width & color
  geom_node_point(size = 5) + 
  geom_node_text(aes(label = name), repel = TRUE) +
  scale_edge_color_viridis() +  # Correct function name
  scale_edge_width_continuous(range = c(0.5, 5)) +  # Adjust thickness
  theme_minimal() +
  ggtitle("Network Graph of Item Co-occurrence")
```
```{r}
library(cluster)

# Compute hierarchical clustering
dist_matrix <- dist(response_Q)  # Compute distance between items
hc <- hclust(dist_matrix, method = "ward.D2")  # Cluster items

# Plot the hierarchical tree
plot(hc, main = "Hierarchical Tree of Q-Matrix", xlab = "Items", ylab = "Distance")
```

