---
title: "IRW Q-matrix estimation"
author: "Wanjing Anya Ma"
date:  "`r Sys.Date()`"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
    
---

# Data Preprocessing
## Load Packages
Let's first load the packages that we need for this chapter. 

```{r, message=FALSE, warning = FALSE, echo = FALSE}
library("knitr") # for rendering the RMarkdown file
library("tidyverse") # for data wrangling 
library(dplyr)
library(mirt)
library('ggpubr')
library(Metrics)
library(hash)
library(ggplot2)
library(GGally)
library(imv)
```
```{r}
library(CDM)
library(NMF)
source('qmatrix_estimation/SNMF-code/utility.R')
source('qmatrix_estimation/SNMF-code/compute_rss_fun.R')
```

```{r echo = FALSE}
# sets how code looks in knitted document
opts_chunk$set(comment = "")

# suppresses warning about grouping 
options(dplyr.summarise.inform = F)
```

# Load IRW
```{r}
#reliability 
dataset <- redivis::user("datapages")$dataset("item_response_warehouse",version='v8.0')

dataset_tables <- dataset$list_tables()
```

```{r}
df <- dataset$table("frac20")$to_data_frame()
```
```{r}
 Q <- df %>% 
     dplyr ::select(-c(id, resp)) %>% 
    unique() %>% 
     dplyr ::arrange(item) %>% 
     dplyr ::select(-c(item))
  
  Q <- Q[, colSums(Q != 0) > 0]
  
  Q <- Q[, order(colnames(Q))]
```
```{r}
Q
```

```{r}
ntimes<-2
```
```{r}
x0 <- df %>% 
  mutate(item = as.integer(substring(item, 6))) %>% 
  arrange(item) 
resp0<-data.frame(irw::long2resp(x0))
id<-resp0$id
resp0$id<-NULL
```
```{r}
resp0
```
# determine the K 
```{r}
R <- resp0
J<-ncol(R)
N<-nrow(R)
JJ<-(J+1)/2+1

rss<-compute_rss_fun(R,JJ)  

#####calculate the st based on rss########################
  st<-rep(0,JJ)
  f<-rss
  ep<-0.5     #????ĸΪ0ʱ??????
  for (j in 2:(JJ-1)) {
      if((f[j]-f[j+1])==0){
        st[j]<-abs(f[j]-f[j-1])/ep
      }else{
        st[j]<-abs(f[j]-f[j-1])/abs(f[j+1]-f[j])
      }
  }
  print(which.max(st))

```

# q_matrix identification 
```{r}
K<-8   
R0<- resp0
 R<-del.zeros(R0)  
 print(nrow(R))

 ######estimate the Q-matrix used the SNMF method
 time1=as.POSIXlt(Sys.time()) 
 R.nmf<- nmf(t(!R),K,method = 'snmf/l') 
 time2=as.POSIXlt(Sys.time())
 use.time=difftime(time2,time1,units="secs")
 print(use.time)     
 
 R.W<-R.nmf@fit@W
 
```
```{r}
q.matrix = matrix(0, nrow = 20, ncol = 2)
```

```{r}
R.W
```
```{r}
R.W_converted <- ifelse(R.W > 1, 1, 0)
```
```{r}
as.matrix(Q)
```
```{r}
R.W
```

```{r}
Q.d<-discreQ_fun(as.matrix(Q),R.W)  
```

```{r}
R.W_converted
```
```{r}
Q
```

```{r}
Q.d
```

