---
title: "Simulation 2"
author: "Wanjing Anya Ma"
date:  "`r Sys.Date()`"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
    
---

# Data Preprocessing
## Load Packages
Let's first load the packages that we need for this chapter. 

```{r, message=FALSE, warning = FALSE, echo = FALSE}
library("knitr") # for rendering the RMarkdown file
library("tidyverse") # for data wrangling 
library(dplyr)
library(mirt)
library('ggpubr')
library(Metrics)
library(hash)
library(ggplot2)
library(GGally)
library(gridExtra)
library(rstudioapi)
library(TAM)
library(mgcv)
library(GDINA)
library(MASS)
library(imv)
library(parallel)
library(irw)
```
```{r}
#remotes::install_github("hansorlee/irwpkg")
source("00funs.R")
```
```{r}
remotes::install_github("hansorlee/irwpkg")
```

```{r echo = FALSE}
# sets how code looks in knitted document
opts_chunk$set(comment = "")

# suppresses warning about grouping 
options(dplyr.summarise.inform = F)
```


# Simulation 2
```{r}
oos.compare.flexible <- function(dat, qm, modeltype, estmethod = "mp", nfolds = 5) {
  resp <- as.data.frame(dat)
  resp$id <- 1:nrow(resp)
  result <- list()

  
  # === Full Sample Mode ===
  # CDM prediction
  p.cdm <- cdm.pr.marg.update(resp[, -ncol(resp)], qm, modeltype, estmethod)
  if (length(p.cdm)==1) {
    return (list(imv_full = NA, imv_mean = NA, imv_sd = 0))
  }
  df.cdm <- do.call("rbind", lapply(1:ncol(resp[, -ncol(resp)]), function(i) {
      data.frame(id = resp$id, item = names(resp)[i], p.cdm = p.cdm[, i])
    }))

  # IRT prediction
  
  irtfit <- mirt(resp[, -ncol(resp)], 1, '2PL', verbose = FALSE)
 
  if (!extract.mirt(irtfit , 'converged')) {
    print("HI")
    return (list(imv_full = NA, imv_mean = NA, imv_sd = NA))
  }

  th.est <- fscores(irtfit)
  est <- coef(irtfit, simplify = TRUE, IRTpars = TRUE)$items
  k <- outer(th.est[, 1], est[, 2], '-')
  k <- matrix(est[, 1], nrow = nrow(resp), ncol = ncol(resp) - 1, byrow = TRUE) * k
  p.irt <- 1 / (1 + exp(-k))

  df.irt <- do.call("rbind", lapply(1:ncol(resp[, -ncol(resp)]), function(i) {
      data.frame(id = resp$id, item = names(resp)[i], p.irt = p.irt[, i])
    }))

  # Long format true responses
  df.true <- resp %>%
  pivot_longer(cols = -id, names_to = "item", values_to = "resp")

  # Merge predictions and compute IMV
  df <- df.true %>%
      left_join(df.cdm, by = c("id", "item")) %>%
      left_join(df.irt, by = c("id", "item"))

  imv_full <- imv::imv.binary(df$resp, df$p.irt, df$p.cdm)
  
  # === K-Fold Mode ===
  resp <- as.data.frame(dat)
  df <- resp %>%
    mutate(id = 1:nrow(resp)) %>%
    pivot_longer(cols = -id, names_to = "item", values_to = "resp")
  df$gr <- sample(1:nfolds, nrow(df), replace = TRUE)

  om <- numeric()
  for (gr in unique(df$gr)) {
    print(gr)
      oos <- df[df$gr == gr, ]
      ins <- df[df$gr != gr, ]

      x <- ins %>%
        dplyr ::select(-gr) %>%
        pivot_wider(names_from = item, values_from = resp)

      id <- x$id
      x <- x[, names(resp)]
      

      # CDM
      p.cdm <- cdm.pr.marg.update(x,Q,modeltype,estmethod)
      
      if (length(p.cdm)==1) {
        return (list(imv_full = NA, imv_mean = NA, imv_sd = 0))
        }
      df.cdm <- do.call("rbind", lapply(1:ncol(resp), function(i) {
        data.frame(id = id, item = names(resp)[i], p.cdm = p.cdm[, i])
      }))

      # IRT
      # IRT with convergence check
      irtfit <- mirt(x, 1, '2PL', verbose = FALSE)
      if (!extract.mirt(irtfit, 'converged')) {
        print("HI")
        return (list(imv_full = NA, imv_mean = NA, imv_sd = NA))
      }
    
      th.est <- fscores(irtfit)
      est <- coef(irtfit, simplify = TRUE, IRTpars = TRUE)$items
      k <- outer(th.est[, 1], est[, 2], '-')
      k <- matrix(est[, 1], nrow = nrow(x), ncol = J, byrow = TRUE) * k
      p.irt <- 1 / (1 + exp(-k))
  

      df.irt <- do.call("rbind", lapply(1:ncol(resp), function(i) {
        data.frame(id = id, item = names(resp)[i], p.irt = p.irt[, i])
      }))

      # Merge and evaluate
      oos_eval <- merge(merge(oos, df.cdm), df.irt)
      om[gr] <- imv::imv.binary(oos_eval$resp, oos_eval$p.irt, oos_eval$p.cdm)
    }
  return(list(imv_full = imv_full, imv_mean = mean(om, na.rm = TRUE), imv_sd = sd(om, na.rm = TRUE)))
  
}
```


```{r}
cdm.sim.2 <- function(N = 500, modeltype = "DINA", attribute = "mvnorm", repetition = 1) {
  Q <- sim30GDINA$simQ
  J <- nrow(Q)
  K <- ncol(Q)
  a <- 0.5
  cutoffs <- qnorm(c(1:K)/(K+1))
  m <- rep(0, K)
  vcov <- matrix(a, K, K)
  diag(vcov) <- 1

  results <- vector("list", repetition)

  for (i in seq_len(repetition)) {
    print("REPETITION ")
    print(i)
    gs <- matrix(runif(J * 2, 0, 0.3), J, 2)

    sim <- switch(attribute,
      independent = simGDINA(N, Q, gs.parm = gs, model = modeltype, gs.args = list(mono.constraint = TRUE)),
      mvnorm = simGDINA(N, Q, gs.parm = gs, model = modeltype,
                        att.dist = "mvnorm",
                        mvnorm.parm = list(mean = m, sigma = vcov, cutoffs = cutoffs)),
      higher.order = {
        theta <- rnorm(N)
        lambda <- data.frame(a = rep(1, K), b = seq(-2, 2, length.out = K))
        simGDINA(N, Q, gs.parm = gs, model = modeltype,
                 gs.args = list(mono.constraint = TRUE),
                 att.dist = "higher.order",
                 higher.order.parm = list(theta = theta, lambda = lambda))
      },
      linear = {
        lin <- list(c(1,2), c(2,3), c(3,4), c(4,5))
        struc <- att.structure(lin, K)
        simGDINA(N, Q, gs.parm = gs, model = modeltype,
                 gs.args = list(mono.constraint = TRUE),
                 att.dist = "categorical", att.prior = struc$att.prob)
      },
      converg = {
        conv <- list(c(1,2), c(2,3), c(2,4), c(3,5), c(4,5))
        struc <- att.structure(conv, K)
        simGDINA(N, Q, gs.parm = gs, model = modeltype,
                 gs.args = list(mono.constraint = TRUE),
                 att.dist = "categorical", att.prior = struc$att.prob)
      },
      diverg = {
        div <- list(c(1,2), c(2,3), c(1,4), c(4,5))
        struc <- att.structure(div, K)
        simGDINA(N, Q, gs.parm = gs, model = modeltype,
                 gs.args = list(mono.constraint = TRUE),
                 att.dist = "categorical", att.prior = struc$att.prob)
      },
      {
        unstruc <- list(c(1,2), c(1,3), c(1,4), c(1,5))
        struc <- att.structure(unstruc, K)
        simGDINA(N, Q, gs.parm = gs, model = modeltype,
                 gs.args = list(mono.constraint = TRUE),
                 att.dist = "categorical", att.prior = struc$att.prob)
      }
    )

    list1 <- oos.compare.flexible(sim$dat, Q, modeltype, estmethod = "MAP", nfold = 5)
    list2 <- oos.compare.flexible(sim$dat, Q, modeltype, estmethod = "mp", nfold = 5)

    result_tbl <- bind_rows(
      as_tibble(list1) %>% mutate(estmethod = "MAP"),
      as_tibble(list2) %>% mutate(estmethod = "mp")
    ) %>% mutate(attribute = attribute, modeltype = modeltype, rep = i)

    results[[i]] <- result_tbl
  }

  final_tbl <- bind_rows(results)
  return(final_tbl)
}
```

```{r}
library(furrr)
library(dplyr)
library(tidyr)
library(purrr)
plan(multisession)
set.seed(123)
simulate_scenario_2_attribute_linear <- function(modeltype = "GDINA") {
  attribute_types <- c("linear", "mvnorm", "higher.order", "independent", "converg", "diverg", "unstructured")
  
  attribute_types <- c("linear")
  
  # Run one simulation per attribute type
  purrr::map_dfr(attribute_types, function(attr) {
    cdm.sim.2(N = 500, modeltype = modeltype, attribute = attr, repetition = 10)
  })
}

```

```{r}
df.sim2.results <- simulate_scenario_2_attribute("GDINA")
```
```{r}
set.seed(123)
df.sim2.results.DINA.1 <- simulate_scenario_2_attribute_linear("DINA")
```

```{r}
df.sim2.results.DINA.1
```
```{r}
set.seed(123)
simulate_scenario_2_attribute_independent<- function(modeltype = "GDINA") {
 
  attribute_types <- c("independent")
  
  # Run one simulation per attribute type
  purrr::map_dfr(attribute_types, function(attr) {
    cdm.sim.2(N = 500, modeltype = modeltype, attribute = attr, repetition = 10)
  })
}

df.sim2.results.DINA.2 <- simulate_scenario_2_attribute_independent("DINA")
```
```{r}
df.sim2.results.DINA.2
```
```{r}
set.seed(123)
simulate_scenario_2_attribute_others<- function(modeltype = "GDINA") {
 
  attribute_types <- c( "mvnorm", "higher.order",  "converg", "diverg", "unstructured")
  
  # Run one simulation per attribute type
  purrr::map_dfr(attribute_types, function(attr) {
    cdm.sim.2(N = 500, modeltype = modeltype, attribute = attr, repetition = 10)
  })
}

df.sim2.results.DINA.3 <- simulate_scenario_2_attribute_others("DINA")
```
```{r}
df.sim2.results.DINA <- rbind(df.sim2.results.DINA.1, df.sim2.results.DINA.2, df.sim2.results.DINA.3)
```
```{r}
write_csv(df.sim2.results.DINA, "simulation_data_update/simulation2_n500_dina.csv")
```
```{r}
df.sim2.results.DINA %>% 
  group_by(attribute, modeltype, estmethod) %>%
  summarise(
    n = sum(!is.na(imv_full)),
    med_imv_full = mean(imv_full, na.rm = TRUE),
    med_imv_mean = mean(imv_mean, na.rm = TRUE),
    .groups = "drop"
  )
```

```{r}
set.seed(123)
simulate_scenario_2_attribute<- function(modeltype = "GDINA") {
 
  attribute_types <- c("linear", "independent", "mvnorm", "higher.order",  "converg", "diverg", "unstructured")
  
  # Run one simulation per attribute type
  purrr::map_dfr(attribute_types, function(attr) {
    print(attr)
    cdm.sim.2(N = 500, modeltype = modeltype, attribute = attr, repetition = 10)
  })
}

df.sim2.results.GDINA <- simulate_scenario_2_attribute("GDINA")
```

```{r}
df.imv.compare.combined <- df.sim2.results.GDINA %>% 
  rbind(df.sim2.results.DINA) %>% 
  group_by(attribute, modeltype, estmethod) %>%
  summarise(
    n = sum(!is.na(imv_full)),
    mean_imv_full = mean(imv_full, na.rm = TRUE),
    mean_imv_oos = mean(imv_mean, na.rm = TRUE),
    sd_imv_full = sd(imv_full, na.rm = TRUE),
    sd_imv_oos = sd(imv_mean, na.rm = TRUE),
    .groups = "drop"
  )
```

```{r}
write_csv(df.sim2.results.GDINA, "simulation_data_update/simulation2_n500_gdina.csv")
```

```{r}
df.sim2.results.GDINA <- read_csv("../simulation_data_update/simulation2_n500_gdina.csv")
df.sim2.results.DINA <- read_csv("../simulation_data_update/simulation2_n500_dina.csv")
```


```{r}
results_median <- results_50_dina %>%
  group_by(attribute, modeltype, estmethod) %>%
  summarise(
    med_imv_full = median(imv_full, na.rm = TRUE),
    med_imv_mean = median(imv_mean, na.rm = TRUE),
    med_imv_sd   = median(imv_sd, na.rm = TRUE),
    .groups = "drop"
  )

results_mean <- results_50_dina %>%
  group_by(attribute, modeltype, estmethod) %>%
  summarise(
    med_imv_full = mean(imv_full, na.rm = TRUE),
    med_imv_mean = mean(imv_mean, na.rm = TRUE),
    med_imv_sd   = mean(imv_sd, na.rm = TRUE),
    .groups = "drop"
  )

results_median
```
```{r}

attribute_types <- c("linear",  "converg", "mvnorm", "higher.order","diverg", "independent",  "unstructured")
df.imv.compare.combined <- df.sim2.results.GDINA %>% 
  rbind(df.sim2.results.DINA) %>% 
  group_by(attribute, modeltype, estmethod) %>%
  summarise(
    n = sum(!is.na(imv_full)),
    mean_imv_full = mean(imv_full, na.rm = TRUE),
    mean_imv_oos = mean(imv_mean, na.rm = TRUE),
    sd_imv_full = sd(imv_full, na.rm = TRUE),
    sd_imv_oos = sd(imv_mean, na.rm = TRUE),
    .groups = "drop"
  )

df_long <- df.imv.compare.combined %>%
  mutate(attribute = factor(attribute, levels = attribute_types)) %>%  # <- key line
  pivot_longer(cols = c(mean_imv_full, mean_imv_oos), 
               names_to = "method", 
               values_to = "mean_imv") %>%
  mutate(sd = case_when(
    method == "mean_imv_full" ~ sd_imv_full,
    method == "mean_imv_oos"  ~ sd_imv_oos
  ))
ggplot(df_long, aes(x = attribute, y = mean_imv, fill = method)) +
  geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.8)) +
  geom_errorbar(aes(ymin = mean_imv - sd, ymax = mean_imv + sd),
                width = 0.5,
                position = position_dodge(width = 0.8)) +
  labs(x = "Hierarchical structures", y = "IMV(2PL, CDM)") +
  theme_minimal() +
  facet_grid(estmethod ~ modeltype) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.spacing = unit(1.5, "lines"),
    strip.text = element_text(size = 12)
  ) +
  scale_fill_manual(
    name = "Method",
    values = c("mean_imv_full" = "#F8766D", "mean_imv_oos" = "#00BFC4"),
    labels = c("mean_imv_full" = "in-sample", "mean_imv_oos" = "out-of-sample fold")
  ) +
  scale_x_discrete(expand = expansion(mult = c(0.1, 0.1)))

```

```{r}
ggsave("../plots_update/simulation2_n500.pdf", width = 6, height = 4)
```

