---
title: "Simulation 2"
author: "Wanjing Anya Ma"
date:  "`r Sys.Date()`"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
    
---

# Data Preprocessing
## Load Packages
Let's first load the packages that we need for this chapter. 

```{r, message=FALSE, warning = FALSE, echo = FALSE}
library("knitr") # for rendering the RMarkdown file
library("tidyverse") # for data wrangling 
library(dplyr)
library(mirt)
library('ggpubr')
library(Metrics)
library(hash)
library(ggplot2)
library(GGally)
library(gridExtra)
library(rstudioapi)
library(TAM)
library(mgcv)
library(GDINA)
library(MASS)
library(imv)
library(parallel)
library(irw)
```
```{r}
#remotes::install_github("hansorlee/irwpkg")
source("bd/00funs.R")
```
```{r}
remotes::install_github("hansorlee/irwpkg")
```

```{r echo = FALSE}
# sets how code looks in knitted document
opts_chunk$set(comment = "")

# suppresses warning about grouping 
options(dplyr.summarise.inform = F)
```
```{r}
oos.compare.flexible <- function(dat, qm, modeltype, estmethod = "mp", nfolds = 5) {
  resp <- as.data.frame(dat)
  resp$id <- 1:nrow(resp)
  result <- list()

  
  # === Full Sample Mode ===
  # CDM prediction
  p.cdm <- cdm.pr.marg.update(resp[, -ncol(resp)], qm, modeltype, estmethod)

  df.cdm <- do.call("rbind", lapply(1:ncol(resp[, -ncol(resp)]), function(i) {
      data.frame(id = resp$id, item = names(resp)[i], p.cdm = p.cdm[, i])
    }))

  # IRT prediction
  irtfit <- mirt(resp[, -ncol(resp)], 1, '2PL')
  th.est <- fscores(irtfit)
  est <- coef(irtfit, simplify = TRUE, IRTpars = TRUE)$items
  k <- outer(th.est[, 1], est[, 2], '-')
  k <- matrix(est[, 1], nrow = nrow(resp), ncol = ncol(resp) - 1, byrow = TRUE) * k
  p.irt <- 1 / (1 + exp(-k))

  df.irt <- do.call("rbind", lapply(1:ncol(resp[, -ncol(resp)]), function(i) {
      data.frame(id = resp$id, item = names(resp)[i], p.irt = p.irt[, i])
    }))

  # Long format true responses
  df.true <- resp %>%
  pivot_longer(cols = -id, names_to = "item", values_to = "resp")

  # Merge predictions and compute IMV
  df <- df.true %>%
      left_join(df.cdm, by = c("id", "item")) %>%
      left_join(df.irt, by = c("id", "item"))

  imv_full <- imv::imv.binary(df$resp, df$p.irt, df$p.cdm)
  
  # === K-Fold Mode ===
  resp <- as.data.frame(dat)
  df <- resp %>%
    mutate(id = 1:nrow(resp)) %>%
    pivot_longer(cols = -id, names_to = "item", values_to = "resp")
  df$gr <- sample(1:nfolds, nrow(df), replace = TRUE)

  om <- numeric()
  for (gr in unique(df$gr)) {
      oos <- df[df$gr == gr, ]
      ins <- df[df$gr != gr, ]

      x <- ins %>%
        dplyr ::select(-gr) %>%
        pivot_wider(names_from = item, values_from = resp)

      id <- x$id
      x <- x[, names(resp)]
      

      # CDM
      p.cdm <- cdm.pr.marg.update(x, qm, modeltype, estmethod)
      df.cdm <- do.call("rbind", lapply(1:ncol(resp), function(i) {
        data.frame(id = id, item = names(resp)[i], p.cdm = p.cdm[, i])
      }))

      # IRT
      irtfit <- mirt(x, 1, '2PL')
      th.est <- fscores(irtfit)
      est <- coef(irtfit, simplify = TRUE, IRTpars = TRUE)$items
      k <- outer(th.est[, 1], est[, 2], '-')
      k <- matrix(est[, 1], nrow = nrow(x), ncol = J, byrow = TRUE) * k
      p.irt <- 1 / (1 + exp(-k))

      df.irt <- do.call("rbind", lapply(1:ncol(resp), function(i) {
        data.frame(id = id, item = names(resp)[i], p.irt = p.irt[, i])
      }))

      # Merge and evaluate
      oos_eval <- merge(merge(oos, df.cdm), df.irt)
      om[gr] <- imv::imv.binary(oos_eval$resp, oos_eval$p.irt, oos_eval$p.cdm)
    }
  return(list(imv_full = imv_full, imv_mean = mean(om), imv_sd = sd(om)))
  
}
```


```{r}
set.seed(123)
Q <- sim30GDINA$simQ
J <- nrow(Q)
K <- ncol(Q)

# Simulation 2
cdm.sim.2 <- function(a, N = 500, modeltype = "DINA", attribute = "mvnorm") {
  print(attribute)
  Q <- sim30GDINA$simQ
  J <- nrow(Q)
  K <- ncol(Q)

  gs <- matrix(runif(J * 2, 0, 0.3), J, 2)
  cutoffs <- qnorm(c(1:K)/(K+1))
  m <- rep(0, K)
  vcov <- matrix(a, K, K)
  diag(vcov) <- 1

  sim <- switch(attribute,
    independent = simGDINA(N, Q, gs.parm = gs, model = modeltype,
                           att.dist = "mvnorm", mvnorm.parm = list(mean = m, sigma = vcov, cutoffs = cutoffs)),
    higher.order = {
      theta <- rnorm(N)
      lambda <- data.frame(a = rep(1, K), b = seq(-2, 2, length.out = K))
      simGDINA(N, Q, gs.parm = gs, model = modeltype,
               att.dist = "higher.order", higher.order.parm = list(theta = theta, lambda = lambda))
    },
    linear = {
      lin <- list(c(1,2), c(2,3), c(3,4), c(4,5))
      struc <- att.structure(lin, K)
      simGDINA(N, Q, gs.parm = gs, model = modeltype,
               att.dist = "categorical", att.prior = struc$att.prob)
    },
    converg = {
      conv <- list(c(1,2), c(2,3), c(2,4), c(4,5), c(3,5))
      struc <- att.structure(conv, K)
      simGDINA(N, Q, gs.parm = gs, model = modeltype,
               att.dist = "categorical", att.prior = struc$att.prob)
    },
    diverg = {
      div <- list(c(1,2), c(2,3), c(1,4), c(4,5))
      struc <- att.structure(div, K)
      simGDINA(N, Q, gs.parm = gs, model = modeltype,
               att.dist = "categorical", att.prior = struc$att.prob)
    },
    {
      unstruc <- list(c(1,2), c(1,3), c(1,4), c(1,5))
      struc <- att.structure(unstruc, K)
      simGDINA(N, Q, gs.parm = gs, model = modeltype,
               att.dist = "categorical", att.prior = struc$att.prob)
    }
  )
  list1 <-oos.compare.flexible(sim$dat, Q, modeltype, estmethod = "MAP", nfold = 5) 
  list2 <- oos.compare.flexible(sim$dat, Q, modeltype, estmethod = "mp", nfold = 5)
  
  result_tbl <- bind_rows(
  as_tibble(list1),
  as_tibble(list2)
  ) %>% mutate(attribute = attribute, modeltype = modeltype)
  return(result_tbl)
}

```
```{r}
library(furrr)
library(dplyr)
library(tidyr)
library(purrr)
plan(multisession)
simulate_scenario_2_attribute <- function(modeltype = "GDINA") {
  attribute_types <- c("independent", "higher.order", "linear", "converg", "diverg", "unstructured")
  
  # Run one simulation per attribute type
  purrr::map_dfr(attribute_types, function(attr) {
    cdm.sim.2(a = 0, N = 500, modeltype = modeltype, attribute = attr)
  })
}

```

```{r}
df.sim2.results <- simulate_scenario_2_attribute("GDINA")
```

```{r}
df.sim2.results
```
```{r}
df.sim2.results.DINA <- simulate_scenario_2_attribute("DINA")
```

```{r}
df.sim2.results.DINA
```
```{r}
df.imv.compare.combined <- rbind(df.sim2.results.DINA, df.sim2.results) %>% 
  mutate(estimate_method = rep(c("MAP", "mp"), length.out = n()))

#write_csv(df.imv.compare.combined, "simulation_data_update/simulation2.csv")
```

```{r}
df_long <- df.imv.compare.combined %>%
  mutate(attribute = fct_inorder(attribute)) %>% 
  pivot_longer(cols = c(imv_full, imv_mean),
               names_to = "method",
               values_to = "mean_imv")

# Create error bar data (set `sd = 0` for mean_imv_all)
df_error <- df_long %>%
  mutate(attribute = fct_inorder(attribute)) %>% 
  mutate(sd = ifelse(method == "imv_mean", df.imv.compare.combined$imv_sd, NA))

ggplot(df_long, aes(x = attribute, y = mean_imv, fill = method)) +
  geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.8)) +
  geom_errorbar(data = df_error, 
                aes(ymin = mean_imv - sd, ymax = mean_imv + sd, x = attribute),
                width = 0.5,
                position = position_dodge(width = 0.8)) +
  labs(x = "Hierarchical structures", y = "IMV(2PL, CDM)") +
  theme_minimal() +
  facet_grid(estimate_method ~ modeltype) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom", 
    strip.text = element_text(size = 12)
  ) +
  scale_fill_manual(
    name = "Method",
    values = c("imv_full" = "#F8766D", "imv_mean" = "#00BFC4"),  # Add your own colors
    labels = c("imv_full" = "in-sample", "imv_mean" = "out-of-sample fold")
  ) +
  scale_x_discrete(expand = expansion(mult = c(0.1, 0.1)))
```


```{r}
ggsave("plots_update/simulation2.pdf", width = 6, height = 4)
```

